In [1]:
import numpy as np
import pandas as  pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
text=['This is a line',
     'This is another line',
     'Completely different line']

In [18]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer #avoids manually building BOW model

In [20]:
cv=CountVectorizer()

In [21]:
cv.fit_transform(text) # now it will treat each line as seperate document

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

* it has stored frequency of words in sparse matrix

In [29]:
sparse_matrix=cv.fit_transform(text) # bag of words model

In [30]:
sparse_matrix.todense() # to see the results 

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

* while dealing with large datasets we should not call these kind of functions bcoz it takes lot of space

In [31]:
cv.vocabulary_ # index of all words in the above matrix

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

# stop word parameter

In [25]:
cv1=CountVectorizer(stop_words='english')

In [26]:
sparse_matrix1=cv1.fit_transform(text) 

In [27]:
sparse_matrix1.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [28]:
cv1.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

# tfidfTransformer: it takes count of word frequency(BOW) and transform it into vector

In [19]:
tfidf=TfidfTransformer()

In [32]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [34]:
# passing BOW to transform TF-IDF (BOW ---> TFIDF)
results=tfidf.fit_transform(sparse_matrix)

In [35]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [36]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

# this all process can be done in one step using TFIDF vectorizer

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tv=TfidfVectorizer()

In [41]:
tv_result=tv.fit_transform(text)

In [42]:
tv_result

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [43]:
tv_result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

* CountVectorizer + TfidfTransformer = TfidfVectorizer
* CountVectorizer ---> BOW
* TfidfTransformer ---> TF-IDF
* TfidfVectorizer ---> BOW + TF-IDF in single step